
version: 1.0.{build}

branches:
  only:
    - main

platform:
  - x64

cache:
  - c:\php-dev -> .appveyor.yml

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_BUILD: vs16
      PHP_VER: 8.2.13
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_BUILD: vs16
      PHP_VER: 8.3.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   VS_BUILD: vs16
    #   PHP_VER: 8.2.0
    #   NATIVE: AVX

build_script:
  - win\build.bat

test_script:
  - win\test.bat
