
version: 1.0.{build}

branches:
  only:
    - main

platform:
  - x64

cache:
  - c:\php-dev -> .appveyor.yml

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_BUILD: vs16
      PHP_VER: 8.2.1
      NATIVE: AVX
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_BUILD: vs16
      PHP_VER: 8.1.14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_BUILD: vs16
      PHP_VER: 7.4.33

build_script:
  - win\build.bat

test_script:
  - win\test.bat
