language: php
sudo: false
group: stable

branches:
  only:
    - main

git:
  depth: 1

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  # Compile:
  - phpize
  - ./configure
  - make

  # Run tests:
  - make test
